# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novelreader', '0002_auto_20180403_0220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together=set([('user', 'novel_id')]),
        ),
    ]
